name: firstworkflow

on:
  push:
    branches: branches:
      - main
jobs:
  job1:
    runs-on: ubuntu:latest
    steps:
      - name: welcomw hello message
        run: "echo welcome to first workflow"
        
