on:
  workflow_dispatch:
    inputs:
      environment:
        description: "choose your env"
        
jobs:
  deploy:
    runs-on: ubuntu:latest
    steps:
    - name: deploy
      run: echo "hello"
      
  
