name: "hello this is first"

on:
  schedule:
    # This runs at 00:00 (midnight) every day
    - cron: "0 0 * * *" 

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: "Say Hello"
        run: echo "Hello World"